version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  groups:
    github-actions:
      patterns:
      - "*"

- package-ecosystem: "gradle"
  directory: "app/"
  schedule:
    interval: "weekly"
  groups:
    gradle:
      patterns:
      - "*"
