name: Build release
run-name: Build artefacts for ${{github.ref_name}}

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  Release:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'

    - name: Set gradle.properties
      env:
        PROPERTIES_BASE64: ${{ secrets.PROPERTIES_BASE64 }}
      run: |
        mkdir -p ~/.gradle
        echo "$PROPERTIES_BASE64" | base64 --decode >~/.gradle/gradle.properties

    - name: Set KeyStore
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      run: echo "$KEYSTORE_BASE64" | base64 --decode >keyStore.jks

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build APK
      run: |
        ./gradlew assembleRelease
        mv app/build/outputs/apk/release/app-release.apk clip_share_client.apk

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: "clip_share_client.apk"
        path: "clip_share_client.apk"
